[package]
name = "mpw"
version = "0.1.0"
authors = ["Uwe Simm <uwe.simm@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "1.11.0"
structopt ="0.3.2"
human-panic = "1.0.3"
scrypt = "0.5.0"
hmac = "0.10.1"
sha2 = "0.9.2"
rpassword = "5.0.0"

[[bin]]
name = "mpw"
path = "src/main.rs"
